name: Release to Maven Central
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Decode signing key
        run: |
          echo "$SIGNING_KEY" | base64 -d > /tmp/private.key
          echo "SIGNING_KEY=$(cat /tmp/private.key)" >> $GITHUB_ENV
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Build & Publish
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY: ${{ env.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew clean publishToSonatype closeAndReleaseSonatypeStagingRepository